### ISSUE TITLE
Publish snapshots from main

### ISSUE THREAD

**Issue by dsyer** [jstachio/jstachio#179] opened 2023-06-16 07:14 UTC
From the README it looks like the project is set up to publish snapshots, but isn't doing it. Might it be a good idea?

**Comment by agentgt** [comment] 2023-06-16 12:20
The issue is GPG as well as other security credentials.

I can set it up as an action but right now it is manual.

**Comment by agentgt** [comment] 2023-06-18 13:25
Oh I see the confusion in the readme. The SNAPSHOT (java)doc is generated on every commit to main but SNAPSHOT jars are not published.

I can set that up but sonatype uptime has been a little sporadic lately and I would rather not deploy constantly to them to ease the burden on them but then again we are not a major project with commits everyday.

However I agree it would be useful particularly when dealing with docker images where you do not want to mount `~/.m2/repository`.

If this would be useful to you let me know and I will try to get it in sometime this week.

**Comment by dsyer** [comment] 2023-06-18 14:29
Not urgent really. The workarounds are easy and well-known. It would just be convenient.

**Comment by agentgt** [comment] 2023-06-29 01:22
Today I pushed 1.2.0-SNAPSHOT into sonatype aka maven central snapshot repo.

It has the latest spring boot stuff.

**Comment by agentgt** [comment] 2023-08-22 23:52
Closing for now as I see it better to do this on a per need basis.

**Closed by agentgt** 2023-08-22 23:52 UTC
Labels: internal
